# megatron actor config, inheriting from trainer/config/actor/actor.yaml
defaults:
  - actor
  # load the reference default config, then apply the fields in the current yaml
  - _self_

_target_: verl.workers.config.McoreActorConfig

strategy: megatron

data_loader_seed: null

load_weight: True

optim:
  _target_: verl.workers.config.McoreOptimizerConfig
  optimizer: adam

  clip_grad: 1.0

  # initial learning rate for warmup, default to 0.0
  lr_warmup_init: 0.0

  lr_decay_steps: null

  # select from constant/linear/cosine/inverse_square_root
  lr_decay_style: constant

  # minimum learning rate, default to 0.0
  min_lr: 0.0

  # select from constant/linear/cosine
  weight_decay_incr_style: constant

  # select from constant/exponential/cosine
  lr_wsd_decay_style: exponential

  lr_wsd_decay_steps: null

  # use checkpoint optimizer parameter scheduler
  use_checkpoint_opt_param_scheduler: False

megatron:

  # Required when using verl.utils.omega_conf_to_dataclass to instantiate dataclass configs
  _target_: verl.workers.config.McoreEngineConfig

  # Whether to offload model parameters to CPU
  param_offload: False

  # Whether to offload gradients to CPU
  grad_offload: False

  # Whether to offload optimizer state to CPU
  optimizer_offload: False

  tensor_model_parallel_size: 1

  expert_model_parallel_size: 1

  expert_tensor_parallel_size: null

  pipeline_model_parallel_size: 1

  virtual_pipeline_model_parallel_size: null

  context_parallel_size: 1

  sequence_parallel: True

  use_distributed_optimizer: True

  use_dist_checkpointing: False

  dist_checkpointing_path: null
  
  # oc.select: default val for ref.megatron.seed
  seed: 42

  # Allow to override Distributed Data Parallel (DDP) config
  override_ddp_config: {}

  # additional transformer config like: num_layers_in_first(/last)_pipeline_stage
  # oc.select: default val for ref.megatron.override_transformer_config
  override_transformer_config:
    # Recompute configuration, same as in megatron.training.arguments
    # default use minimal performance-interference recompute methods
    # Recompute granualarity, choices: ["full", "selective"]
    recompute_granularity: null

    # Recompute modules, multiple choices: ["core_attn", "moe_act", "layernorm", "mla_up_proj", "mlp", "moe"]
    # Please use correct module in matched model
    recompute_modules: ["core_attn"]

    # 'uniform', 'block'
    # 'uniform' divides the total number of transformer layers and checkpoints the input activation of each chunk
    # 'block' checkpoints the specified number of layers per pipeline stage at the specified granularity
    recompute_method: "uniform"

    # 'full' will checkpoint the entire transformer layer and 'selective' only checkpoints memory intensive part of attention
    recompute_num_layers: null

    use_loss_chunk: False

    compute_probs_in_model: False
    
    compute_lm_head_fp32: False

    # auto or flash
    attention_backend: 'auto'

    pipeline_model_parallel_method: 'uniform'
  
    use_cpu_initialization: null
  
    gradient_accumulation_fusion: True
  
    async_tensor_model_parallel_allreduce: True
  
    batch_p2p_comm: True
  
    deallocate_pipeline_outputs: True
  
    mtp_loss_scaling_factor: 0.1
  
    init_method_std: 0.01
  
    bias_activation_fusion: True
  
    persist_layer_norm: True
  
    distribute_saved_activations: False
  
    moe_router_load_balancing_type: 'none'
  
    moe_grouped_gemm: True
  
    moe_aux_loss_coeff: 0.0
  
    cp_comm_type: 'p2p'
  
    imagemlp_recompute: False

    gated_linear_unit: True

    masked_softmax_fusion: False

    bias_dropout_fusion: False

    attention_softmax_in_fp32: False

    add_bias_linear: False

    use_lf_gate: True

    use_yuanvl: True

    attention_dropout: 0.1

    use_apex_rmsnorm: False

    encoder_pipeline_model_parallel_size: 0

    selectable_expert: False

    pipeline_model_parallel_blocks: null

    pipeline_model_parallel_comm_backend: null
    num_layers_per_virtual_pipeline_stage: null
    standalone_embedding_stage: False
    hierarchical_context_parallel_sizes: null
    moe_extended_tp: False
    perform_initialization: True
    no_sync_func: null
    grad_sync_func: null
    param_sync_func: null
    deterministic_mode: False
    enable_autocast: False
    use_te_rng_tracker: False
    tp_comm_overlap: False
    tp_comm_bulk_wgrad: True
    tp_comm_bulk_dgrad: True
    tp_comm_overlap_ag: True
    tp_comm_overlap_rs: True
    tp_comm_overlap_rs_dgrad: False
    tp_comm_split_ag: True
    tp_comm_atomic_ag: False
    tp_comm_split_rs: True
    tp_comm_atomic_rs: False
    cross_entropy_loss_fusion: False
    cross_entropy_fusion_impl: 'native'
    tp_comm_overlap_disable_qkv: False
    tp_comm_overlap_disable_fc1: False
    tp_comm_bootstrap_backend: 'nccl'
    variable_seq_lengths: True
    overlap_p2p_comm: False
    batch_p2p_sync: True
    use_ring_exchange_p2p: False
    defer_embedding_wgrad_compute: False
    wgrad_deferral_limit: 0
    pipeline_model_parallel_split_rank: null
    overlap_p2p_comm_warmup_flush: False
    microbatch_group_size_per_vp_stage: 2
    cpu_offloading: False
    cpu_offloading_num_layers: 0
    _cpu_offloading_context: null
    cpu_offloading_activations: True
    cpu_offloading_weights: True
    barrier_with_L1_time: True
    mtp_num_layers: null
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    account_for_embedding_in_pipeline_split: False
    account_for_loss_in_pipeline_split: False
    softmax_scale: null
    num_query_groups: null
    hidden_dropout: 0.0
    fp32_residual_connection: False
    apply_residual_connection_post_layernorm: False
    layernorm_zero_centered_gamma: False
    add_qkv_bias: False
    activation_func_fp8_input_store: False
    rotary_interleaved: False
    window_size: null
    normalization: 'RMSNorm'
    qk_layernorm: False
    calculate_per_token_loss: False
    multi_latent_attention: False
    init_model_with_meta_device: False
    apply_query_key_layer_scaling: False
    disable_bf16_reduced_precision_matmul: False
    memory_efficient_layer_norm: False
    apply_rope_fusion: False
    fp8: null
    fp8_recipe: 'delayed'
    fp8_param: False
    fp8_margin: 0
    fp8_interval: 1
    fp8_amax_history_len: 1
    fp8_amax_compute_algo: 'most_recent'
    fp8_wgrad: True
    fp8_dot_product_attention: False
    fp8_multi_head_attention: False
    tp_only_amax_red: False
    first_last_layers_bf16: False
    num_layers_at_start_in_bf16: 1
    num_layers_at_end_in_bf16: 1
    moe_shared_expert_intermediate_size: null
    moe_shared_expert_overlap: False
    moe_layer_freq: 1
    use_attention_router: False
    moe_router_topk_limited_devices: null
    moe_router_num_groups: null
    moe_router_group_topk: null
    moe_router_pre_softmax: False
    moe_router_topk_scaling_factor: null
    moe_router_score_function: 'softmax'
    moe_router_dtype: null
    moe_router_enable_expert_bias: False
    moe_router_bias_update_rate: 0.001
    moe_use_legacy_grouped_gemm: False
    moe_z_loss_coeff: null
    moe_input_jitter_eps: null
    moe_token_dropping: False
    moe_token_dispatcher_type: 'alltoall'
    moe_enable_deepep: False
    moe_per_layer_logging: False
    moe_expert_capacity_factor: null
    moe_pad_expert_input_to_capacity: False
    moe_token_drop_policy: 'probs'
    moe_layer_recompute: False
    moe_permute_fusion: False
    moe_apply_probs_on_input: False
    enable_cuda_graph: False
    cuda_graph_use_single_mempool: False
    cuda_graph_retain_backward_graph: False
    cuda_graph_warmup_steps: 3
    external_cuda_graph: False
    cuda_graph_scope: 'full'
    clone_scatter_output_in_embedding: True
    disable_parameter_transpose_cache: False
    config_logger_dir: ''
    flash_decode: False
    inference_rng_tracker: False
    mrope_section: null
    is_hybrid_model: False
    mamba_state_dim: 128
    mamba_head_dim: 64
    mamba_num_groups: 8
    heterogeneous_block_specs: False
    loss_chunk: 1024
  # oc.select: default val for ref.megatron.use_mbridge
  use_mbridge: False

# profile the actor model in `update_policy` 
profile:

  # turn it on when you want to profile the actor model
  use_profile: False

  # list, you can specify the ranks to profile
  profile_ranks: null

  # start step in update_policy
  step_start: -1

  # end step
  step_end: -1

  # the path to save the profile result
  save_path: null
